steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ghl-private-mcp
      - --source=.
      - --quiet
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-secrets=GHL_PIT_TOKEN=GHL_PIT_TOKEN:latest,GHL_LOCATION_ID=GHL_LOCATION_ID:latest

options:
  logging: CLOUD_LOGGING_ONLY
